### ISSUE TITLE
Add -f option (or something similar) to overwrite tests when using rrtest create

### ISSUE THREAD

**Issue by pkmoore** [pkmoore/rrapper#31]
If the test directory already exists things fail until you manually delete it.  This is a usability concern if you mis-created a test and want to recreate it.

I propose a better error message in this case and maybe the option to use -f to force-overwrite (i.e. delete and recreate) a particular test.

**Comment by ex0dus-0x** [comment]
One thing a user can do instead of re-running `rrtest create` would be to use `rrtest configure` in order to reselect the correct trace line, etc. By doing so, the helper methods in `rrtest` should override whatever has been written in the CrashSimulator-generated trace directory.

**Comment by pkmoore** [comment]
I went ahead and added this feature.  You can now do --force=YES to overwrite the directory in question.  I also added a check to print a descriptive error message if the test already exists
