### ISSUE TITLE
Better rr replay / strace alignment

### ISSUE THREAD

**Issue by pkmoore** [pkmoore/rrapper#34]
I've been investigating this and it seems like if we filter out certain RR events we can get pretty close to a perfect match between rr events and strace output.  For an example, check out the attached files.  I've filtered system call exits, EXIT events, and INSTRUCTION_TRAP events.

[rrout.txt](https://github.com/pkmoore/rrapper/files/2578057/rrout.txt)
[strace_out.txt](https://github.com/pkmoore/rrapper/files/2578059/strace_out.txt)

It seems like the easiest way to do this is to record the rr output, filter it, and look up the correct event number.

**Comment by alyptik** [comment]
@pkmoore do you still have the original file without filtering system call exits, EXIT events, and INSTRUCTION_TRAP events, and if so would you mind uploading that as well?

**Comment by pkmoore** [comment]
I can re-generate it but I have another idea that I'm going to try I think.  I _think_ we can modify rr to write out event numbers for the system calls.  I'm considering doing this using strace comment lines.  Something like:
```
+++ Event: 146 +++
open("test.txt", O_RDONLY) = 3
```

**Comment by alyptik** [comment]
These changes are being reviewed in [#12](https://github.com/pkmoore/rr/pull/12) in the  [pkmoore/rr](https://github.com/pkmoore/rr) repository.

I'm not really sure how to directly reference PRs from other repositories, so if someone ekse knows how please feel free to do so, thanks.

**Comment by pkmoore** [comment]
@alyptik @ex0dus-0x 
I think I've addressed this problem with some modifications to rr: https://github.com/pkmoore/rr/pull/12
and some modifications to rrapper: https://github.com/pkmoore/rrapper/pull/49

I'm going to announce this to the students and we need to test it pretty heavily.  There's a fair bit of offset work to pick the correct lines so the code isn't the clearest.  It should probably be cleaned up once we're confident this works.

**Comment by pkmoore** [comment]
Merged
