### ISSUE TITLE
injection fails for gettimeofday

### ISSUE THREAD

**Issue by mnm678** [pkmoore/rrapper#46]
When replaying time I got the following error:
```  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/syscallreplay/time_handlers.py", line 414, in gettimeofday_entry_handler
    seconds = int(syscall_object.args[0].value.strip('{}'))
ValueError: invalid literal for int() with base 10: 'tv_sec=1542315437'
Failed to complete trace
Injector for event:rec_pid 156:27064 failed
```

The call it was injecting is here:
 ```
gettimeofday({tv_sec=1542315437, tv_usec=734041}, NULL) = 0
```

**Comment by pkmoore** [comment]
This is a weird one.  The folks at strace decided to add names to the fields tv_sec and tv_usec that weren't there previously.  These calls used to look like 
```
gettimeofday({<seconds>, <useconds>}, NULL) = 0
```

I've pushed changes to the syscallreplay module that should handle both cases.  Rerun the pip install on requirements.txt with the --update switch to pick the changes up.  Let me know if something breaks!
