### ISSUE TITLE
Add support for 85(readlink)

### ISSUE THREAD

**Issue by akbisw** [pkmoore/rrapper#50]
Ran into it while testing HEAD (grabs the header from HTTP GET call to a website). Testing time anomaly on it

**Comment by pkmoore** [comment]
I've added support for this call in https://github.com/pkmoore/rrapper/pull/54.  Please pull the branch associated with this pull request and give it a shot.  Everything should be fine so I'll merge it into master here in a little bit unless I hear that its definitely broken.

This required changes to both rrapper and the syscallreplay module so you'll need to do a full reinstall of the rapper side of things (pip install with --update, python setup.py install, etc).

**Comment by pkmoore** [comment]
merged
