### ISSUE TITLE
Empty Result of rrtest configure

### ISSUE THREAD

**Issue by mnm678** [pkmoore/rrapper#51]
When running rrtest configure to align to the time call in `crontab -l` there were no possible events listed.

**Comment by pkmoore** [comment]
Two things to try here:

You could pull the output_event_number branches of rr and rrrapper and see if it will self-align correctly.

Another alternative is to change directory into the the directory of the test in .crashsim and run
```
RR_LOG=ReplaySession rr replay -a
```
This will run a rr replay session under autopilot and report the event numbers for you to choose from.

Let me know if this doesn't help out.  There may be weird permissions issues around cron stuff that I haven't run into before.

**Comment by mnm678** [comment]
I still can't get it to work.

The RR_LOG command failed with this message:
```
[FATAL /home/alex/rr/src/main.cc:243:main() errno: ENOENT] Module import failed
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x4a)[0x810920]
rr(_ZN2rr15notifying_abortEv+0x6a)[0x8108d1]
rr(_ZN2rr12FatalOstreamD1Ev+0x36)[0x6d2428]
rr(main+0x245)[0x8271ac]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0xb76d3e81]
rr(+0x21a9dc)[0x61a9dc]
=== End rr backtrace
Aborted (core dumped)
```

In the output_event_number branch the `rrtest configure --name cron --traceline 144` command resulted in:
```
Traceback (most recent call last):
  File "/home/alex/rrapper/crashsim/bin/rrtest", line 11, in <module>
    load_entry_point('rrapper==0.1.0', 'console_scripts', 'rrtest')()
  File "build/bdist.linux-i686/egg/src/rrtest.py", line 285, in main
IndexError: list index out of range
```

**Comment by pkmoore** [comment]
You'll get that last error when rr can't find some python modules it needs.  This is usually because your virtual environment isn't activated or is missing the stuff installed  by pip install -r requirements.txt

**Comment by pkmoore** [comment]
I think this is resolved now.  Feel free to re-open if it isn't.
