### ISSUE TITLE
When rr create fails, the last strace is echoed instead of an error message

### ISSUE THREAD

**Issue by mm7259** [pkmoore/rrapper#60]
I was trying to create a test which was meant to fail since I didn't have the correct pre-reqs. However, the `rrtest create` command ran without any error and echoed the last successful strace. 

Thanks!

**Comment by pkmoore** [comment]
As a note to whatever dev ends up looking at this problem.  What ends up happening is the call to rr record made by rrtest create fails but we do not detect this situation and handle it.  As a result, the code that is supposed to echo the contents of strace_out.strace ends up getting executed and the contents of whatever strace_out.strace file is present in the current directory are output.

  We need to capture the fact that rr record has failed and abort execution with a helpful error.

**Comment by alyptik** [comment]
Fixed in PR #65.

**Comment by pkmoore** [comment]
Merged! Thanks!
